server:
  port: 0 # Permitir que Railway asigne un puerto dinámico

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Habilita descubrimiento automático en Eureka
          lower-case-service-id: true # Asegura que los nombres de los servicios sean en minúsculas
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "https://frontend-eight-liard-29.vercel.app" # Dominio del frontend en Vercel
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: service-registry
          uri: lb://service-registry
          predicates:
            - Path=/registry/**

eureka:
  client:
    service-url:
      defaultZone: https://service-registry-production-8dd6.up.railway.app/eureka/
    register-with-eureka: true # Permitir que API Gateway se registre en Eureka
    fetch-registry: true # Obtener la lista de servicios desde Eureka
  instance:
    prefer-ip-address: true # Usar la IP en lugar del hostname para evitar problemas de DNS
