server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "https://frontend-eight-liard-29.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: https://auth-service-production-c807.up.railway.app
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: https://user-service-production-9d8d.up.railway.app
          predicates:
            - Path=/users/**

        - id: order-service
          uri: https://order-service-production.up.railway.app
          predicates:
            - Path=/orders/**

        - id: product-service
          uri: https://product-service-production-3da2.up.railway.app
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: https://cart-service-master-production.up.railway.app
          predicates:
            - Path=/cart/**

        - id: category-service
          uri: https://category-service-master-production.up.railway.app
          predicates:
            - Path=/categories/**

        - id: notification-service
          uri: https://notification-service-master-production.up.railway.app
          predicates:
            - Path=/notifications/**

        - id: service-registry
          uri: https://service-registry-master-production.up.railway.app
          predicates:
            - Path=/registry/**
